# Generated by Django 5.2.3 on 2025-07-03 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Sale)')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.products')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.productsku')),
            ],
            options={
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
